language: c

env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=6.0
 - RACKET_VERSION=6.0.1
 - RACKET_VERSION=HEAD

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

install:

before_script:

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
 - /usr/racket/bin/raco pkg install --deps search-auto --link frog
 - /usr/racket/bin/raco test -x -p frog

after_script:
