language: c

env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=HEAD

before_install:
 - curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.3/install-racket.sh | sh

install:

before_script:

script:
 # Note: Must duplicate `deps` from info.rkt here.
 - /usr/racket/bin/raco pkg install --deps search-auto markdown find-parent-dir
 - /usr/racket/bin/raco pkg install --link frog
 - /usr/racket/bin/raco link frog # for frog/widgets in templates.rkt
 - cd frog
 - /usr/racket/bin/raco make frog.rkt
 - /usr/racket/bin/raco test -x .

after_script:
