language: c

env:
 - RACKET_VERSION=5.3.5
 - RACKET_VERSION=5.3.6
 - RACKET_VERSION=6.0
 - RACKET_VERSION=HEAD

before_install:
# Note: Important to pipe this to `bash` not to `sh`.
- curl -L https://github.com/greghendershott/travis-racket/releases/download/v0.5/install-racket.sh | bash

install:

before_script:

script:
 - cd ..   # Travis did a cd into the dir. Back up, for the next:
 - /usr/racket/bin/raco pkg install --deps search-auto --link frog
 - /usr/racket/bin/raco test -x -p frog

after_script:
